// Categorias: mains | sides | desserts | beverages | seasonal | chef
export const MENU = [
  {
    id: "vaca-atolada",
    name: "Vaca Atolada (Ossobuco)",
    image: "/images/vaca-atolada.jpg",
    category: "mains",
    tags: ["beef", "halal"],
    brief: {
      pt: "Ossobuco com polenta cremosa e rúcula cítrica.",
      en: "Braised beef shank with creamy polenta and citrus arugula.",
      ar: "عظم لحم بقر مطهو ببطء مع بولينتا كريمية وجرجير حمضي.",
    },
    description: {
      pt: "Clássico mineiro de fazenda, a ‘vaca atolada’ nasceu do cozimento lento do ossobuco até soltar colágeno e sabor. Servimos com polenta cremosa ao estilo do interior — fogo baixo e paciência.",
      en: "A countryside Minas classic. Slow-braised beef shank releases collagen and deep flavor. Served with velvety polenta cooked low and slow.",
      ar: "طبق ريفي من ميناس جيرايس. يُطهى عظم لحم البقر ببطء حتى يذوب الكولاجين ويبرز الطعم العميق مع بولينتا ناعمة.",
    },
    nutrition: { kcal: 720, carbs: 45, protein: 58, fat: 32 },
    allergens: ["milk"],
    halal: true,
  },
  {
    id: "feijoada-costela",
    name: "Feijoada de Costela",
    image: "/images/feijoada-costela.jpg",
    category: "mains",
    tags: ["beef", "halal"],
    brief: {
      pt: "Feijão preto com costela, farofa de banana e vinagrete.",
      en: "Black beans with beef ribs, banana farofa and vinaigrette.",
      ar: "فاصوليا سوداء مع ضلع لحم بقر وفاروفا الموز وصلصة خل.",
    },
    description: {
      pt: "Nossa feijoada é 100% halal e sem porco. Inspirada nas reuniões de domingo, leva costela bovina lentamente cozida, feijão preto, farofa de banana e arroz soltinho.",
      en: "Our feijoada is fully halal (no pork). Sunday-style: slow beef ribs, black beans, banana farofa and fluffy rice.",
      ar: "فيجوادا حلال بالكامل بدون لحم خنزير: ضلع لحم بقر مطهو ببطء مع فاصوليا سوداء وفاروفا الموز وأرز مفلفل.",
    },
    nutrition: { kcal: 690, carbs: 60, protein: 42, fat: 28 },
    allergens: [],
    halal: true,
  },
  {
    id: "picanha-grelhada",
    name: "Picanha Grelhada",
    image: "/images/picanha-grelhada.jpg",
    category: "chef",
    tags: ["beef", "halal"],
    brief: {
      pt: "Com risoto de cogumelos, polenta verde e molho de pimenta do reino.",
      en: "With mushroom risotto, green polenta and black-pepper sauce.",
      ar: "مع ريزوتو الفطر وبولينتا خضراء وصلصة فلفل أسود.",
    },
    description: {
      pt: "A picanha, corte-símbolo dos churrascos brasileiros, ganhou fama nos anos 1960 pelo equilíbrio entre maciez e capa de gordura. Selamos em alta temperatura para crosta dourada e suculência.",
      en: "Picanha — Brazil’s iconic steak — rose in the 1960s for its tender meat and fat cap. We sear hot for a golden crust and juicy center.",
      ar: "البيكانيا هي قطعة لحم أيقونية في البرازيل تتميّز بطراوتها وغطائها الدهني؛ تُحمر بحرارة عالية لقشرة ذهبية وقلب عصاري.",
    },
    nutrition: { kcal: 680, carbs: 35, protein: 55, fat: 34 },
    allergens: ["milk"],
    halal: true,
  },
  {
    id: "pao-de-queijo",
    name: "Pão de Queijo",
    image: "/images/pao-de-queijo.jpg",
    category: "sides",
    tags: ["vegetarian"],
    brief: {
      pt: "Tradicional, macio e quentinho.",
      en: "Traditional, soft and warm.",
      ar: "خبز الجبن البرازيلي — طري ودافئ.",
    },
    description: {
      pt: "Receita mineira com polvilho e queijo curado. Assamos para casquinha fina e miolo elástico.",
      en: "Minas-style tapioca-starch dough with aged cheese. Baked for thin crust and stretchy crumb.",
      ar: "وصفة ميناس مع نشا الكسافا وجبن معتّق، تُخبز لقشرة رقيقة وحشوة مطاطية.",
    },
    nutrition: { kcal: 320, carbs: 30, protein: 9, fat: 18 },
    allergens: ["milk", "eggs"],
    halal: true,
  },
  {
    id: "polenta-frita",
    name: "Polenta Frita",
    image: "/images/polenta-frita.jpg",
    category: "sides",
    tags: [],
    brief: {
      pt: "Dourada por fora, cremosa por dentro.",
      en: "Crispy outside, creamy inside.",
      ar: "مقرمشة من الخارج وكريمية من الداخل.",
    },
    description: {
      pt: "Herança ítalo-brasileira: polenta firme cortada e frita, servida com molho de tomate da casa.",
      en: "Italo-Brazilian staple: firm polenta cut and fried, served with house tomato sauce.",
      ar: "وصفة إيطالية-برازيلية: بولينتا صلبة تُقطع وتُقلى مع صلصة طماطم منزلية.",
    },
    nutrition: { kcal: 360, carbs: 48, protein: 6, fat: 15 },
    allergens: [],
    halal: true,
  },
  {
    id: "encanto-de-coco",
    name: "Encanto de Coco",
    image: "/images/encanto-de-coco.jpg",
    category: "desserts",
    tags: ["vegetarian"],
    brief: {
      pt: "Pudim de coco com caramelo claro.",
      en: "Coconut flan with light caramel.",
      ar: "فلان جوز الهند بكراميل خفيف.",
    },
    description: {
      pt: "Sobremesa afetiva de festas populares. Textura sedosa, doçura equilibrada e coco fresco.",
      en: "A festive classic: silky texture, balanced sweetness and fresh coconut.",
      ar: "حلوى شعبية ذات قوام ناعم وحلاوة متوازنة وجوز هند طازج.",
    },
    nutrition: { kcal: 410, carbs: 44, protein: 8, fat: 22 },
    allergens: ["milk", "eggs"],
    halal: true,
  },
  {
    id: "doce-da-roca-com-gelo",
    name: "Doce da Roça com Gelo",
    image: "/images/doce-da-roca-com-gelo.jpg",
    category: "desserts",
    tags: ["vegetarian"],
    brief: {
      pt: "Abóbora cremosa com especiarias e sorvete artesanal.",
      en: "Spiced creamy pumpkin with artisanal ice cream.",
      ar: "قرع كريمي متبّل مع آيس كريم مصنوع يدوياً.",
    },
    description: {
      pt: "Abóbora cozida lentamente com cravo e canela, lembrança das cozinhas de fazenda.",
      en: "Pumpkin slowly cooked with clove and cinnamon — farm kitchen memories.",
      ar: "قرع يُطهى ببطء مع القرنفل والقرفة على طريقة المزارع.",
    },
    nutrition: { kcal: 380, carbs: 55, protein: 6, fat: 14 },
    allergens: ["milk"],
    halal: true,
  },
  {
    id: "pamonha",
    name: "Pamonha (Sazonal)",
    image: "/images/pamonha.jpg",
    category: "seasonal",
    tags: ["vegetarian"],
    brief: {
      pt: "Clássico de milho verde — doce ou salgada.",
      en: "Green-corn classic — sweet or savory.",
      ar: "طبق الذرة الخضراء الكلاسيكي — حلو أو مالح.",
    },
    description: {
      pt: "Milho ralado fresco, cozido em palha. Tradição junina que perfuma a casa inteira.",
      en: "Fresh grated corn cooked in husk. A June-festival tradition.",
      ar: "ذرة طازجة مبشورة تُطهى داخل القشور — تقليد مهرجانات يونيو.",
    },
    nutrition: { kcal: 300, carbs: 58, protein: 6, fat: 6 },
    allergens: [],
    halal: true,
  },
  {
    id: "sol-do-cerrado",
    name: "Sol do Cerrado",
    image: "/images/sol-do-cerrado.jpg",
    category: "beverages",
    tags: [],
    brief: {
      pt: "Manga com maracujá, hortelã e toque cítrico.",
      en: "Mango & passion fruit with mint and citrus.",
      ar: "مانجو مع فاكهة العاطفة والنعناع ولمسة حمضية.",
    },
    description: {
      pt: "Refresco sem álcool que homenageia frutas do cerrado.",
      en: "Alcohol-free refresher honoring Brazilian savanna fruits.",
      ar: "مشروب منعش دون كحول يحتفي بثمار السافانا البرازيلية.",
    },
    nutrition: { kcal: 160, carbs: 38, protein: 1, fat: 0 },
    allergens: [],
    halal: true,
  },
  {
    id: "uva-limao-gelo",
    name: "Uva & Limão Gelo",
    image: "/images/uva-limao-gelo.jpg",
    category: "beverages",
    tags: [],
    brief: {
      pt: "Suco de uva integral com limão e hortelã.",
      en: "Pure grape juice with lemon and mint.",
      ar: "عصير عنب طبيعي مع ليمون ونعناع.",
    },
    description: {
      pt: "Clássico sem álcool, cítrico e perfumado.",
      en: "A classic alcohol-free, citrusy and aromatic.",
      ar: "منعش وخالٍ من الكحول بنفحات حمضية وعطرية.",
    },
    nutrition: { kcal: 150, carbs: 36, protein: 1, fat: 0 },
    allergens: [],
    halal: true,
  }
];
