import { LOCALES } from "./i18n";

export const CATEGORIES = {
  MAINS: "mains",
  SIDES: "sides",
  DESSERTS: "desserts",
  BEVERAGES: "beverages",
  SEASONAL: "seasonal",
  CHEF: "chef",
};

export const MENU = [
  {
    id: "vaca-atolada",
    image: "/images/vaca-atolada.jpg",
    category: CATEGORIES.MAINS,
    badge: CATEGORIES.MAINS,
    title: {
      pt: "Vaca Atolada (Ossobuco)",
      en: "Vaca Atolada (Ossobuco)",
      ar: "ڤاكا أتولادا (أوسوبوكو)",
    },
    short: {
      pt: "Ossobuco com polenta cremosa e rúcula cítrica.",
      en: "Slow-cooked ossobuco with creamy polenta and citrus arugula.",
      ar: "أوسوبوكو مطهو ببطء مع بولينتا كريمية وجرجير بنكهة الحمضيات.",
    },
    long: {
      pt: "Clássico de Minas e do interior do Brasil. O osso com tutano cozinha lentamente, dando sabor profundo. Servimos com polenta cremosa e rúcula temperada com limão, lembrando a mesa de domingo em família.",
      en: "A countryside classic from Brazil. The marrow bone simmers low and slow for deep flavor. Served with creamy polenta and lemony arugula — a Sunday family-table memory.",
      ar: "طبق تقليدي من الريف البرازيلي. يُطهى العظم ذو النخاع ببطء لنكهة عميقة. يُقدَّم مع بولينتا كريمية وجرجير بالليمون، كوجبة عائلية يوم الأحد.",
    },
    nutrition: { kcal: 690, carbs: 38, protein: 45, fat: 38 },
    allergens: ["lactose"],
    tags: ["beef", "halal"],
  },
  {
    id: "feijoada-costela",
    image: "/images/feijoada-costela.jpg",
    category: CATEGORIES.MAINS,
    badge: CATEGORIES.MAINS,
    title: {
      pt: "Feijoada de Costela",
      en: "Beef Rib Feijoada",
      ar: "فيجوادا ضلع البقر",
    },
    short: {
      pt: "Feijão preto com costela, farofa de banana e vinagrete.",
      en: "Black beans with beef ribs, banana farofa and vinaigrette.",
      ar: "فاصوليا سوداء مع أضلاع بقر وفاروفا الموز وصلصة الخل.",
    },
    long: {
      pt: "Nossa versão da feijoada é 100% halal: costela bovina lentamente cozida no feijão, acompanhada de farofa de banana, arroz e vinagrete. Conforto brasileiro, sem carne de porco.",
      en: "Our feijoada is 100% halal: beef ribs simmered in black beans, served with banana farofa, rice and vinaigrette. Brazilian comfort — no pork.",
      ar: "نسختنا من الفيحوادا حلال 100٪: أضلاع بقر تُسلق مع الفاصوليا السوداء وتُقدّم مع فاروفا الموز والأرز وصلصة الخل. بدون لحم خنزير.",
    },
    nutrition: { kcal: 720, carbs: 52, protein: 42, fat: 35 },
    allergens: [],
    tags: ["beef", "halal", "gluten-free"],
  },
  {
    id: "picanha-grelhada",
    image: "/images/picanha-grelhada.jpg",
    category: CATEGORIES.CHEF,
    badge: CATEGORIES.CHEF,
    title: {
      pt: "Picanha Grelhada",
      en: "Grilled Picanha",
      ar: "بيكانيا مشوية",
    },
    short: {
      pt: "Com risoto de cogumelos, polenta verde e molho de pimenta do reino.",
      en: "With mushroom risotto, green-corn polenta and black-pepper sauce.",
      ar: "مع ريزوتو الفطر وبولينتا الذرة الخضراء وصلصة الفلفل الأسود.",
    },
    long: {
      pt: "Corte favorito dos churrascos, grelhado ao ponto, com risoto de cogumelos e polenta verde (milho verde batido). Finalizamos com molho cremoso de pimenta-do-reino.",
      en: "A beloved Brazilian cut, grilled to perfection, paired with mushroom risotto and green-corn polenta, finished with a creamy black-pepper sauce.",
      ar: "قطعة لحم برازيلية محبوبة تُشوى بإتقان، تُقدَّم مع ريزوتو الفطر وبولينتا الذرة الخضراء وصلصة الفلفل الأسود الكريمية.",
    },
    nutrition: { kcal: 780, carbs: 40, protein: 48, fat: 44 },
    allergens: ["lactose"],
    tags: ["beef", "halal"],
  },
  {
    id: "pao-de-queijo",
    image: "/images/pao-de-queijo.jpg",
    category: CATEGORIES.SIDES,
    badge: CATEGORIES.SIDES,
    title: {
      pt: "Pão de Queijo",
      en: "Pão de Queijo",
      ar: "خبز الجبن",
    },
    short: {
      pt: "Tradicional, macio e quentinho.",
      en: "Traditional, soft and warm.",
      ar: "تقليدي، طري ودافئ.",
    },
    long: {
      pt: "Receita mineira com polvilho e queijo. Sem glúten por natureza, perfeito para compartilhar.",
      en: "Minas-style tapioca-cheese rolls. Naturally gluten-free and perfect for sharing.",
      ar: "خبز تاپيوكا بالجبن على طريقة ميناس. خالٍ من الغلوتين بطبيعته ومثالي للمشاركة.",
    },
    nutrition: { kcal: 290, carbs: 28, protein: 9, fat: 15 },
    allergens: ["lactose"],
    tags: ["vegetarian", "gluten-free"],
  },
  {
    id: "polenta-frita",
    image: "/images/polenta-frita.jpg",
    category: CATEGORIES.SIDES,
    badge: CATEGORIES.SIDES,
    title: { pt: "Polenta Frita", en: "Crispy Polenta", ar: "بولينتا مقلية" },
    short: {
      pt: "Dourada por fora, cremosa por dentro.",
      en: "Crispy outside, creamy inside.",
      ar: "مقرمشة من الخارج وكريمية من الداخل.",
    },
    long: {
      pt: "Palitos de polenta fritos e temperados. Acompanha molho da casa.",
      en: "Seasoned fried polenta sticks. Served with house dip.",
      ar: "أصابع بولينتا مقلية متبلة. تُقدَّم مع صلصة المطعم.",
    },
    nutrition: { kcal: 360, carbs: 42, protein: 6, fat: 18 },
    allergens: [],
    tags: ["vegetarian"],
  },
  {
    id: "encanto-de-coco",
    image: "/images/encanto-de-coco.jpg",
    category: CATEGORIES.DESSERTS,
    badge: CATEGORIES.DESSERTS,
    title: { pt: "Encanto de Coco", en: "Coconut Delight", ar: "لذة جوز الهند" },
    short: {
      pt: "Pudim de coco com caramelo claro.",
      en: "Coconut flan with light caramel.",
      ar: "كرامل بجوز الهند.",
    },
    long: {
      pt: "Inspirado nas sobremesas do Norte/Nordeste, cremoso e perfumado.",
      en: "Inspired by northern Brazilian desserts — creamy and fragrant.",
      ar: "مستوحى من الحلويات البرازيلية الشمالية — كريمي وعطِر.",
    },
    nutrition: { kcal: 420, carbs: 48, protein: 6, fat: 22 },
    allergens: ["lactose", "eggs"],
    tags: ["vegetarian"],
  },
  {
    id: "uva-limao-gelo",
    image: "/images/uva-limao-gelo.jpg",
    category: CATEGORIES.BEVERAGES,
    badge: CATEGORIES.BEVERAGES,
    title: { pt: "Uva & Limão Gelo", en: "Grape & Lemon Ice", ar: "عصير العنب والليمون" },
    short: {
      pt: "Suco de uva integral com limão e hortelã.",
      en: "Pure grape juice with lemon and mint.",
      ar: "عصير عنب خالص مع الليمون والنعناع.",
    },
    long: {
      pt: "Refrescante e sem álcool. Adoçado levemente, perfeito para o clima do Qatar.",
      en: "Refreshing and alcohol-free. Lightly sweetened — perfect for Qatar's heat.",
      ar: "منعش وخالٍ من الكحول، حلاوة خفيفة — مناسب لحرارة قطر.",
    },
    nutrition: { kcal: 120, carbs: 29, protein: 1, fat: 0 },
    allergens: [],
    tags: ["non-alcoholic", "vegan"],
  },
];
