// src/menuData.js
// Caminhos partem de /public (ex.: /images/arquivo.jpg)

export const MENU = [
  // ---------------- PRATOS (mains)
  {
    id: "picanha-grelhada",
    category: "mains",
    name: "Picanha Grelhada",
    image: "/images/picanha-grelhada.jpg",
    desc: { pt: "Picanha na brasa, ponto perfeito e suculência." },
    tags: ["Halal", "Beef"],
  },
  {
    id: "fraldinha-inteira",
    category: "mains",
    name: "Fraldinha Inteira",
    image: "/images/fraldinha-inteira.jpg",
    desc: { pt: "Corte macio servido na tábua, perfeito para compartilhar." },
    tags: ["Halal", "Beef"],
  },
  {
    id: "vaca-atolada",
    category: "mains",
    name: "Vaca Atolada (Ossobuco)",
    image: "/images/vaca-atolada.jpg",
    desc: { pt: "Ossobuco com polenta cremosa e rúcula cítrica." },
    tags: ["Halal", "Beef", "Dairy"],
  },
  {
    id: "feijoada-costela",
    category: "mains",
    name: "Feijoada de Costela",
    image: "/images/feijoada-costela.jpg",
    desc: { pt: "Feijão preto com costela, farofa de banana e vinagrete." },
    tags: ["Halal", "Beef"],
  },
  {
    id: "moqueca-baiana",
    category: "mains",
    name: "Moqueca Baiana",
    image: "/images/moqueca-baiana.jpg",
    desc: { pt: "Peixe no leite de coco, urucum/dendê e coentro." },
    tags: ["Halal", "Seafood"],
  },
  {
    id: "galinhada-caipira",
    category: "mains",
    name: "Galinhada Caipira",
    image: "/images/galinhada-caipira.jpg",
    desc: { pt: "Arroz de quintal, frango suculento e cheiro-verde." },
    tags: ["Halal", "Chicken"],
  },
  {
    id: "rubacao",
    category: "mains",
    name: "Rubacão",
    image: "/images/rubacao.jpg",
    desc: { pt: "Arroz, feijão de corda, queijo de coalho e carne seca." },
    tags: ["Halal"],
  },
  {
    id: "hamburguer-de-picanha",
    category: "mains",
    name: "Hambúrguer de Picanha",
    image: "/images/hamburguer-de-picanha.jpg",
    desc: { pt: "Blend de picanha na chapa, pão macio e maionese da casa." },
    tags: ["Halal", "Beef"],
  },
  {
    id: "lasanha-banana",
    category: "mains",
    name: "Lasanha de Banana",
    image: "/images/lasanha-banana.jpg",
    desc: { pt: "Clássico criativo com camadas de banana e queijo." },
    tags: ["Vegetarian", "Dairy"],
  },
  {
    id: "pe-de-serra",
    category: "mains",
    name: "Pé-de-Serra",
    image: "/images/pe-de-serra.jpg",
    desc: { pt: "Carne ao ponto com tempero da roça e acompanhamentos." },
    tags: ["Halal", "Beef"],
  },

  // ---------------- ENTRADAS / APPETIZERS
  {
    id: "pao-de-queijo",
    category: "appetizers",
    name: "Pão de Queijo da Casa",
    image: "/images/pao-de-queijo.jpg",
    desc: { pt: "Casquinha crocante, miolo macio — receita de família." },
    tags: ["Vegetarian", "Dairy"],
  },
  {
    id: "pao-de-alho",
    category: "appetizers",
    name: "Pão de Alho",
    image: "/images/pao-de-alho.jpg",
    desc: { pt: "Tostado na brasa com manteiga de alho." },
    tags: ["Vegetarian", "Dairy"],
  },
  {
    id: "polenta-frita",
    category: "appetizers",
    name: "Polenta Frita",
    image: "/images/polenta-frita.jpg",
    desc: { pt: "Bastões crocantes por fora, macios por dentro." },
    tags: ["Vegetarian"],
  },
  {
    id: "mandioca-frita",
    category: "appetizers",
    name: "Mandioca Frita",
    image: "/images/mandioca-frita.jpg",
    desc: { pt: "Maciez por dentro, crocância por fora. Vai bem com tudo." },
    tags: ["Vegetarian"],
  },
  {
    id: "pasteis-brasileiros",
    category: "appetizers",
    name: "Pastéis Brasileiros",
    image: "/images/pasteis-brasileiros.jpg",
    desc: { pt: "Seleção de recheios clássicos, massa fina e sequinha." },
    tags: [],
  },
  {
    id: "coxinhas-de-costela",
    category: "appetizers",
    name: "Coxinhas de Costela",
    image: "/images/coxinhas-de-costela.jpg",
    desc: { pt: "Massa leve, recheio suculento de costela desfiada." },
    tags: ["Beef"],
  },
  {
    id: "farofa-de-castanha",
    category: "appetizers",
    name: "Farofa de Castanha",
    image: "/images/farofa-de-castanha.jpg",
    desc: { pt: "Crocrante, amanteigada e perfumada — acompanha os pratos." },
    tags: ["Vegetarian"],
  },

  // ---------------- SOBREMESAS
  {
    id: "mandioca-real",
    category: "desserts",
    name: "Mandioca Real",
    image: "/images/mandioca-real.jpg",
    desc: { pt: "Bolo cremoso de mandioca com coco." },
    tags: ["Dessert", "Dairy", "Gluten"],
  },
  {
    id: "encanto-de-coco",
    category: "desserts",
    name: "Encanto de Coco",
    image: "/images/encanto-de-coco.jpg",
    desc: { pt: "Cocada cremosa servida gelada." },
    tags: ["Dessert", "Dairy"],
  },
  {
    id: "doce-da-roca-com-gelo",
    category: "desserts",
    name: "Doce da Roça com Gelo",
    image: "/images/doce-da-roca-com-gelo.jpg",
    desc: { pt: "Doce caseiro da fazenda, servido gelado." },
    tags: ["Dessert"],
  },
  // sazonal mas sobremesa — ficará na aba Sazonais
  {
    id: "pamonha",
    category: "seasonal",
    name: "Pamonha Doce (Sazonal)",
    image: "/images/pamonha.jpg",
    desc: { pt: "Clássico de milho verde — disponível em épocas de safra." },
    tags: ["Seasonal", "Dessert"],
  },

  // ---------------- BEBIDAS
  {
    id: "amazon-breeze",
    category: "beverages",
    name: "Amazon Breeze",
    image: "/images/amazon-breeze.jpg",
    desc: { pt: "Refrescância de frutas amazônicas." },
    tags: ["Drink"],
  },
  {
    id: "blueberry-coco-fizz",
    category: "beverages",
    name: "Blueberry & Coco Fizz",
    image: "/images/blueberry-coco-fizz.jpg",
    desc: { pt: "Mirtilo com toque de coco e borbulhas." },
    tags: ["Drink"],
  },
  {
    id: "caipile-classico",
    category: "beverages",
    name: "Caipilé Clássico",
    image: "/images/caipile-classico.jpg",
    desc: { pt: "Clássico gelado com frutas cítricas." },
    tags: ["Drink"],
  },
  {
    id: "frescor-da-amazonia",
    category: "beverages",
    name: "Frescor da Amazônia",
    image: "/images/frescor-da-amazonia.jpg",
    desc: { pt: "Notas verdes e frutadas — refrescante." },
    tags: ["Drink"],
  },
  {
    id: "sol-do-cerrado",
    category: "beverages",
    name: "Sol do Cerrado",
    image: "/images/sol-do-cerrado.jpg",
    desc: { pt: "Cítrico e aromático como o nosso bioma." },
    tags: ["Drink"],
  },
  {
    id: "uva-limao-gelo",
    category: "beverages",
    name: "Uva, Limão & Gelo",
    image: "/images/uva-limao-gelo.jpg",
    desc: { pt: "Combinação azedinha e gelada." },
    tags: ["Drink"],
  },
  {
    id: "verao-brasil",
    category: "beverages",
    name: "Verão Brasil",
    image: "/images/verao-brasil.jpg",
    desc: { pt: "Copo vibrante com frutas da estação." },
    tags: ["Drink"],
  },
  {
    id: "vitamina-do-cerrado",
    category: "beverages",
    name: "Vitamina do Cerrado",
    image: "/images/vitamina-do-cerrado.jpg",
    desc: { pt: "Cremosa e nutritiva com frutas do cerrado." },
    tags: ["Drink", "Dairy"],
  },

  // ---------------- ITENS EXTRA (caso use)
  {
    id: "placeholder",
    category: "appetizers",
    name: "Da Casa",
    image: "/images/placeholder.jpg",
    desc: { pt: "Item temporário da casa." },
    tags: [],
  },
];